// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6t6lWni1Bkv0jzcJuGxMB0ah00hkUyoo',
    appId: '1:59319593263:web:67153481097d011a6c59da',
    messagingSenderId: '59319593263',
    projectId: 'mishkat-learning-555',
    authDomain: 'mishkat-learning-555.firebaseapp.com',
    storageBucket: 'mishkat-learning-555.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEyLLc2cogAzkK5LbY9ZlZtyq3z-UqZCo',
    appId: '1:59319593263:android:12a9563c39d5425f6c59da',
    messagingSenderId: '59319593263',
    projectId: 'mishkat-learning-555',
    storageBucket: 'mishkat-learning-555.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcdGLbKvWN1imZq0qTIDNsfoVZ7ZwmotM',
    appId: '1:59319593263:ios:8ef3a8a0a84ed5d66c59da',
    messagingSenderId: '59319593263',
    projectId: 'mishkat-learning-555',
    storageBucket: 'mishkat-learning-555.firebasestorage.app',
    iosBundleId: 'com.mishkatapps.mishkatlearning',
  );
}
