// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are only configured for web in this project.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6t6lWni1Bkv0jzcJuGxMB0ah00hkUyoo',
    appId: '1:59319593263:web:e404e16105fb9ebf6c59da',
    messagingSenderId: '59319593263',
    projectId: 'mishkat-learning-555',
    authDomain: 'mishkat-learning-555.firebaseapp.com',
    storageBucket: 'mishkat-learning-555.firebasestorage.app',
  );
}
